name: Deploy to Ubuntu Server1

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
      
    - name: 디버깅: 현재 디렉토리
      run: |
        pwd
        ls -al
      
    - name: Build Docker image
      run: docker build -t login-app .

    - name: Save Docker image to tar file
      run: docker save login-app > login-app.tar

    - name: Copy JAR to Server via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: target/*.jar
        target: /home/ubuntu/bokgi
        strip_components: 1

    - name: Run App on Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker stop login-app || true
          docker rm login-app || true
          docker load < /home/ubuntu/bokgi/login-app.tar
          docker run -d --name login-app -p 8080:8080 login-app


